version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
      - "patchpilot"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
